### PR TITLE
Reword debian package description

### PR DESCRIPTION
**Pull request by anayrat**
Hello,

This should address this issue raised on Debian: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=974644

First line is for short description. Subsequent lines are for
extended description: https://www.debian.org/doc/debian-policy/ch-controlfields.html#description

Regards,

### CODE REVIEW

**Comment by df7cb** [comment]
Hi,
can you also rebase/merge the commit on top of 1.1.2?

At the moment there is a diff between the (non-debian/) files between the 1.1.2 tag and your branch. (This is why maintaining the debian/ directory in the upstream repository is unfortunately hard...)

**Comment by anayrat** [comment]
Hello @df7cb !

It should be ok? Here is my got log from my branch:
```
commit a31b72cc4ac4ec48740b317b4f99dbbd80d4debb (HEAD -> debian_packaging, origin/debian_packaging)
Author: Adrien Nayrat <adrien_nayrat@ultimatesoftware.com>
Date:   Mon Nov 16 09:56:27 2020 +0100

    Reword debian package description
    
    First line is for short description. Subsequent lines are for
    extended description.

commit 38e5d3b7f81eb56951b279e3516e3612f63891e9 (upstream/master, origin/master, origin/HEAD, master)
Author: Alexey Kondratov <kondratov.aleksey@gmail.com>
Date:   Wed Nov 11 13:39:40 2020 +0300

    Bump PGXN release to 1.1.2
```

**Comment by ololobus** [comment]
I did 38e5d3b after releasing v1.1.2, so it is not included there. It is only required for PGXN (I wonder how many people do use it, but I was asked about it about a year ago).

That way, just tell me what suits best you in order to release deb package :) I can:

1. Merge these PR (if it is ready), merge master into stable and just move current v1.1.2 on top of the stable.
2. Or I can do the same, but tag new v1.1.3 if you need a distinguishable tag for some reason.

**Comment by df7cb** [comment]
A third variant could be to have the packaging on a "debian" branch that doesn't have the unreleased changes since the last tag.
Please don't move existing tags as people will then have different tarballs.

**Comment by ololobus** [comment]
Hm, it makes sense, but let us clarify how it make look. Currently we do some changes in `master`, then when everything seems to be fine I merge it into `stable` and tag new release.

That way, current branch `stable` works exactly how you proposed, i.e. now it does not contain any changes since the last v1.1.2. So maybe we can continue using `stable` that way and there is no need in additional `debian` branch?

**Comment by df7cb** [comment]
The "stable" branch works only if there are no changes to be made to the debian/ directory. But for that idea, we don't even need a branch, I can easily build from some tag or even a git hash. What doesn't work is pulling debian/ changes from one branch, while taking the rest of the source from elsewhere.

Or you commit the changes to the "stable" branch, and merge them into master.

**Comment by ololobus** [comment]
Thanks, now I think that I got it. In other words, you need a branch, where the main code corresponds to the latest tag (e.g. `stable` branch), but you can also update `debian` directory there, when needed.

So maybe this will work well:

1. We create a branch on top of `stable` called `debian`.
2. We put `debian` directory there.
3. When you need to change anything in the packaging, you just send a PR to this branch.
4. When we release a new version/tag, we simply rebase `debian` on top of new `stable`. Or we can merge new `stable` into `debian` if you prefer merge to rebase.

Would this make things easier for you?

**Comment by ololobus** [comment]
Just pushed [debian branch](https://github.com/postgrespro/pg_wait_sampling/tree/debian) based on top of `stable` (v1.1.2). So if this will work for you, then just rebase your PR on top of `debian` branch and I will merge it there.

**Comment by anayrat** [comment]
Looks good to me, do you agree @df7cb ?

**Comment by df7cb** [comment]
Hi,
the plan looks good.

To enable us to get package updates done without going through pull requests, could you give Adrien and my push access to the  `debian` branch? Otherwise the whole idea of having less work because the packaging is in the same repo is moot and we should better move the packaging to salsa.debian.org or the like.

Thanks.

**Comment by ololobus** [comment]
OK, accept an invitation and I will give you an access to the `debian` branch.

**Comment by ololobus** [comment]
I have changed the target merge branch of PR to `debian`, but I think that you should rebase you branch on top of it or remove commit `38e5d3b`, @anayrat.

**Comment by df7cb** [comment]
Thanks @ololobus!

I've cherry-picked this as 9fbd8345713.

**Comment by df7cb** [comment]
Updated Debian packages are on their way, thanks all!

**Pull request closed without merging**
